/**
 * Complete set of documents an accrual accounting business needs on file.
 * Used by the Accounting documents hub and sample seeding.
 */

export type AccountingDocGroup =
  | "Sales cycle"
  | "Purchase cycle"
  | "Cash & bank"
  | "Payroll & claims"
  | "Projects & requests"
  | "Fleet"
  | "POS"
  | "Inventory"
  | "Fixed assets & capital"
  | "Books & journals"
  | "Tax & compliance";

export type AccountingDocumentDef = {
  id: string;
  group: AccountingDocGroup;
  label: string;
  description: string;
  module: string;
  /** Storage module when different from the UI module (e.g. banking for receipts). */
  storageModule?: string;
  entityKey: string;
  href: string;
  /** Can print / PDF through the document engine. */
  printable: boolean;
  /** Why accountants keep this document. */
  purpose: string;
};

export const ACCOUNTING_DOCUMENT_GROUPS: AccountingDocGroup[] = [
  "Sales cycle",
  "Purchase cycle",
  "Cash & bank",
  "Payroll & claims",
  "Projects & requests",
  "Fleet",
  "POS",
  "Inventory",
  "Fixed assets & capital",
  "Books & journals",
  "Tax & compliance",
];

export const REQUIRED_ACCOUNTING_DOCUMENTS: AccountingDocumentDef[] = [
  // —— Sales ——
  {
    id: "sales-quotes",
    group: "Sales cycle",
    label: "Sales quotes / Pro forma invoices",
    description: "Price offers before a firm order",
    module: "sales",
    entityKey: "sales-quotes",
    href: "/sales?view=sales-quotes",
    printable: true,
    purpose: "Quote to customer; often used as a pro forma for import / advance payment.",
  },
  {
    id: "sales-orders",
    group: "Sales cycle",
    label: "Sales orders",
    description: "Confirmed customer orders",
    module: "sales",
    entityKey: "sales-orders",
    href: "/sales?view=sales-orders",
    printable: true,
    purpose: "Evidence of the sales commitment before delivery and invoicing.",
  },
  {
    id: "delivery-notes",
    group: "Sales cycle",
    label: "Delivery notes",
    description: "Proof of goods delivered",
    module: "sales",
    entityKey: "delivery-notes",
    href: "/sales?view=delivery-notes",
    printable: true,
    purpose: "Supports revenue recognition and inventory movement.",
  },
  {
    id: "sales-invoices",
    group: "Sales cycle",
    label: "Sales invoices",
    description: "Tax invoices to customers",
    module: "sales",
    entityKey: "sales-invoices",
    href: "/sales?view=sales-invoices",
    printable: true,
    purpose: "Primary AR source document; posts revenue, VAT and receivables.",
  },
  {
    id: "credit-notes",
    group: "Sales cycle",
    label: "Credit notes",
    description: "Returns, allowances, billing corrections",
    module: "sales",
    entityKey: "credit-notes",
    href: "/sales?view=credit-notes",
    printable: true,
    purpose: "Reverses or reduces sales invoices and VAT output.",
  },
  {
    id: "late-payment-fees",
    group: "Sales cycle",
    label: "Late payment fees",
    description: "Interest or penalties on overdue invoices",
    module: "sales",
    entityKey: "late-payment-fees",
    href: "/sales?view=late-payment-fees",
    printable: true,
    purpose: "Other income document when charging overdue balances.",
  },
  {
    id: "billable-time",
    group: "Sales cycle",
    label: "Billable time",
    description: "Chargeable hours",
    module: "sales",
    entityKey: "billable-time",
    href: "/sales?view=billable-time",
    printable: true,
    purpose: "Supports service revenue before it is invoiced.",
  },
  {
    id: "billable-expenses",
    group: "Sales cycle",
    label: "Billable expenses",
    description: "Rechargeable costs",
    module: "sales",
    entityKey: "billable-expenses",
    href: "/sales?view=billable-expenses",
    printable: true,
    purpose: "Costs recovered from customers on invoices.",
  },
  {
    id: "recurring-sales-invoices",
    group: "Sales cycle",
    label: "Recurring sales invoices",
    description: "Retainers and subscriptions",
    module: "sales",
    entityKey: "recurring-sales-invoices",
    href: "/sales?view=recurring-sales-invoices",
    printable: false,
    purpose: "Template that generates periodic tax invoices.",
  },
  {
    id: "revenue-contracts",
    group: "Sales cycle",
    label: "Revenue contracts",
    description: "IFRS 15 performance obligations",
    module: "sales",
    entityKey: "revenue-contracts",
    href: "/sales?view=revenue-contracts",
    printable: true,
    purpose: "Longer-term contracts where revenue is recognised over time.",
  },

  // —— Purchases ——
  {
    id: "purchase-quotes",
    group: "Purchase cycle",
    label: "Purchase quotes",
    description: "Supplier price offers",
    module: "purchases",
    entityKey: "purchase-quotes",
    href: "/purchases?view=purchase-quotes",
    printable: true,
    purpose: "Compare supplier prices before committing.",
  },
  {
    id: "purchase-orders",
    group: "Purchase cycle",
    label: "Purchase orders",
    description: "Authorised buys",
    module: "purchases",
    entityKey: "purchase-orders",
    href: "/purchases?view=purchase-orders",
    printable: true,
    purpose: "Internal control — only ordered goods should be received and paid.",
  },
  {
    id: "goods-receipts",
    group: "Purchase cycle",
    label: "Goods receipts (GRN)",
    description: "Stock received notes",
    module: "purchases",
    entityKey: "goods-receipts",
    href: "/purchases?view=goods-receipts",
    printable: true,
    purpose: "Evidence goods arrived before the supplier bill is booked.",
  },
  {
    id: "purchase-invoices",
    group: "Purchase cycle",
    label: "Purchase invoices / bills",
    description: "Supplier tax invoices",
    module: "purchases",
    entityKey: "purchase-invoices",
    href: "/purchases?view=purchase-invoices",
    printable: true,
    purpose: "Primary AP source document; posts purchases, input VAT and payables.",
  },
  {
    id: "debit-notes",
    group: "Purchase cycle",
    label: "Debit notes",
    description: "Supplier returns / short deliveries",
    module: "purchases",
    entityKey: "debit-notes",
    href: "/purchases?view=debit-notes",
    printable: true,
    purpose: "Reduces AP and recovers input VAT on returns.",
  },
  {
    id: "recurring-purchase-invoices",
    group: "Purchase cycle",
    label: "Recurring purchase invoices",
    description: "Standing supplier bills",
    module: "purchases",
    entityKey: "recurring-purchase-invoices",
    href: "/purchases?view=recurring-purchase-invoices",
    printable: false,
    purpose: "Rent, subscriptions and other periodic costs.",
  },

  // —— Cash ——
  {
    id: "receipts",
    group: "Cash & bank",
    label: "Receipts",
    description: "Money received",
    module: "receipts-payments",
    storageModule: "banking",
    entityKey: "receipts",
    href: "/receipts-payments?view=receipts",
    printable: true,
    purpose: "Clears receivables or books other cash inflows.",
  },
  {
    id: "payments",
    group: "Cash & bank",
    label: "Payments",
    description: "Money paid out",
    module: "receipts-payments",
    storageModule: "banking",
    entityKey: "payments",
    href: "/receipts-payments?view=payments",
    printable: true,
    purpose: "Clears payables or books other cash outflows.",
  },
  {
    id: "inter-account-transfers",
    group: "Cash & bank",
    label: "Inter-account transfers",
    description: "Bank ↔ cash movements",
    module: "banking",
    entityKey: "inter-account-transfers",
    href: "/banking?view=inter-account-transfers",
    printable: true,
    purpose: "Keeps bank and cash books reconciled when funds move internally.",
  },
  {
    id: "reconciliations",
    group: "Cash & bank",
    label: "Bank reconciliations",
    description: "Statement vs books",
    module: "banking",
    entityKey: "reconciliations",
    href: "/banking?view=reconciliations",
    printable: true,
    purpose: "Monthly control that cash in the ledger matches the bank.",
  },

  // —— Payroll ——
  {
    id: "payslips",
    group: "Payroll & claims",
    label: "Payslips",
    description: "Employee pay advice",
    module: "payroll",
    entityKey: "payslips",
    href: "/payroll?view=payslips",
    printable: true,
    purpose: "Gross-to-net with PAYE and NSSF — required payroll record.",
  },
  {
    id: "recurring-payslips",
    group: "Payroll & claims",
    label: "Recurring payslips",
    description: "Standing payroll runs",
    module: "payroll",
    entityKey: "recurring-payslips",
    href: "/payroll?view=recurring-payslips",
    printable: false,
    purpose: "Templates for monthly salary cycles.",
  },
  {
    id: "statutory-remittances",
    group: "Payroll & claims",
    label: "Statutory remittances",
    description: "PAYE / NSSF filings",
    module: "payroll",
    entityKey: "statutory-remittances",
    href: "/payroll?view=statutory-remittances",
    printable: true,
    purpose: "Evidence of remitting payroll taxes and social security.",
  },
  {
    id: "expense-claims",
    group: "Payroll & claims",
    label: "Expense claims",
    description: "Staff reimbursements",
    module: "expense-claims",
    entityKey: "expense-claims",
    href: "/expense-claims?view=expense-claims",
    printable: true,
    purpose: "Approves and posts employee out-of-pocket costs.",
  },
  {
    id: "leave-requests",
    group: "Payroll & claims",
    label: "Leave requests",
    description: "HR leave approvals",
    module: "payroll",
    entityKey: "leave-requests",
    href: "/payroll?view=leave-requests",
    printable: false,
    purpose: "Leave approvals — Requestor → HOD → HR → Approved.",
  },
  {
    id: "payment-requests",
    group: "Projects & requests",
    label: "Payment requests",
    description: "Financial / project payment requests",
    module: "projects",
    entityKey: "payment-requests",
    href: "/projects?view=payment-requests",
    printable: true,
    purpose: "Request funds for projects, departments, or contractors before payment.",
  },
  {
    id: "general-requests",
    group: "Projects & requests",
    label: "General requests",
    description: "General request — Requestor → Accounts Assistant → GM → CEO → Finance",
    module: "general-requests",
    storageModule: "requests",
    entityKey: "general-requests",
    href: "/general-requests",
    printable: true,
    purpose: "Open requests for any need, not limited to contractors or projects.",
  },
  {
    id: "oral-payment-requests",
    group: "Projects & requests",
    label: "Oral payment requests",
    description: "Oral payment requisition — Requestor → Accounts Assistant → GM → CEO → Finance",
    module: "oral-payment-requests",
    storageModule: "requests",
    entityKey: "oral-payment-requests",
    href: "/oral-payment-requests",
    printable: true,
    purpose:
      "Separate requisition procedure for oral payments (not project payment requests).",
  },
  {
    id: "fuel-requests",
    group: "Fleet",
    label: "Fuel requests",
    description: "Fleet fuel authorisations",
    module: "fleet",
    entityKey: "fuel-requests",
    href: "/fleet?view=fuel-requests",
    printable: true,
    purpose: "Approve fuel before fill-up; fulfill to create a posted fuel log.",
  },
  {
    id: "fuel-logs",
    group: "Fleet",
    label: "Fuel logs",
    description: "Posted fuel fills",
    module: "fleet",
    entityKey: "fuel-logs",
    href: "/fleet?view=fuel-logs",
    printable: true,
    purpose: "Records litres and cost; posts Dr Fuel Expense / Cr Bank or Cash.",
  },
  {
    id: "trip-requests",
    group: "Fleet",
    label: "Trip requests",
    description: "Fleet trip authorisations",
    module: "fleet",
    entityKey: "trip-requests",
    href: "/fleet?view=trip-requests",
    printable: true,
    purpose: "Approve vehicle trips before departure; complete to update odometer.",
  },
  {
    id: "maintenance-requests",
    group: "Fleet",
    label: "Maintenance requests",
    description: "Fleet vehicle service requests",
    module: "fleet",
    entityKey: "maintenance-requests",
    href: "/fleet?view=maintenance-requests",
    printable: true,
    purpose: "Request and complete vehicle maintenance; posts Motor Vehicle Expense when Completed.",
  },
  {
    id: "pos-sales",
    group: "POS",
    label: "POS sales",
    description: "Point-of-sale tickets",
    module: "pos",
    entityKey: "pos-sales",
    href: "/pos?view=pos-sales",
    printable: true,
    purpose: "Counter sales with tender, VAT, inventory, and COGS.",
  },
  {
    id: "pos-returns",
    group: "POS",
    label: "POS returns",
    description: "POS refunds",
    module: "pos",
    entityKey: "pos-returns",
    href: "/pos?view=pos-returns",
    printable: true,
    purpose: "Refunds tender and reverses stock / COGS.",
  },
  {
    id: "cash-sessions",
    group: "POS",
    label: "Cash sessions",
    description: "Till open / close",
    module: "pos",
    entityKey: "cash-sessions",
    href: "/pos?view=cash-sessions",
    printable: false,
    purpose: "Opening float and counted cash; variance posts to Cash Over/Short.",
  },
  {
    id: "daily-closings",
    group: "POS",
    label: "Daily closings",
    description: "End-of-day register summary",
    module: "pos",
    entityKey: "daily-closings",
    href: "/pos?view=daily-closings",
    printable: true,
    purpose: "Summarises tender totals and deposits cash from till to bank.",
  },
  {
    id: "requisitions",
    group: "Projects & requests",
    label: "Material Requests",
    description: "Material requests for projects (stores issue or procurement path)",
    module: "projects",
    entityKey: "requisitions",
    href: "/projects?view=requisitions",
    printable: true,
    purpose:
      "Request materials for a project: Initiator → QS → PM → Stores, or procurement path when stock is low.",
  },
  {
    id: "procurement-list",
    group: "Projects & requests",
    label: "Procurement list",
    description: "Material / purchase planning for projects",
    module: "projects",
    entityKey: "procurement-list",
    href: "/projects?view=procurement-list",
    printable: true,
    purpose: "Plan and track materials or services needed for a project.",
  },

  // —— Inventory ——
  {
    id: "stock-in",
    group: "Inventory",
    label: "Stock in",
    description: "Receive inventory",
    module: "inventory",
    entityKey: "stock-in",
    href: "/inventory?view=stock-in",
    printable: true,
    purpose: "Adds quantity into a warehouse/location and increases inventory on hand.",
  },
  {
    id: "inventory-transfers",
    group: "Inventory",
    label: "Inventory transfers",
    description: "Location moves",
    module: "inventory",
    entityKey: "inventory-transfers",
    href: "/inventory?view=inventory-transfers",
    printable: true,
    purpose: "Tracks stock between warehouses without a sale.",
  },
  {
    id: "inventory-write-offs",
    group: "Inventory",
    label: "Inventory write-offs",
    description: "Damage, loss, theft",
    module: "inventory",
    entityKey: "inventory-write-offs",
    href: "/inventory?view=inventory-write-offs",
    printable: true,
    purpose: "Removes stock and books the expense.",
  },
  {
    id: "inventory-sales",
    group: "Inventory",
    label: "Inventory sales",
    description: "Sell stock directly",
    module: "inventory",
    entityKey: "inventory-sales",
    href: "/inventory?view=inventory-sales",
    printable: true,
    purpose: "Reduces stock and posts sales revenue plus COGS to P&L / balance sheet.",
  },
  {
    id: "production-orders",
    group: "Inventory",
    label: "Production orders",
    description: "Manufacturing / assembly",
    module: "inventory",
    entityKey: "production-orders",
    href: "/inventory?view=production-orders",
    printable: true,
    purpose: "Converts components into finished goods.",
  },
  {
    id: "stocktakes",
    group: "Inventory",
    label: "Stocktakes",
    description: "Physical counts",
    module: "inventory",
    entityKey: "stocktakes",
    href: "/inventory?view=stocktakes",
    printable: true,
    purpose: "Period-end inventory verification.",
  },
  {
    id: "landed-costs",
    group: "Inventory",
    label: "Landed costs",
    description: "Freight, duty, clearing",
    module: "inventory",
    entityKey: "landed-costs",
    href: "/inventory?view=landed-costs",
    printable: true,
    purpose: "Capitalises import costs into inventory value.",
  },

  // —— Assets ——
  {
    id: "fixed-assets",
    group: "Fixed assets & capital",
    label: "Fixed assets register",
    description: "PPE master list",
    module: "assets",
    entityKey: "fixed-assets",
    href: "/assets?view=fixed-assets",
    printable: true,
    purpose: "Asset cost, location and carrying amount.",
  },
  {
    id: "depreciation-entries",
    group: "Fixed assets & capital",
    label: "Depreciation entries",
    description: "Periodic PPE charge",
    module: "assets",
    entityKey: "depreciation-entries",
    href: "/assets?view=depreciation-entries",
    printable: true,
    purpose: "Monthly / annual depreciation journals.",
  },
  {
    id: "intangible-assets",
    group: "Fixed assets & capital",
    label: "Intangible assets",
    description: "Software, licences, goodwill",
    module: "assets",
    entityKey: "intangible-assets",
    href: "/assets?view=intangible-assets",
    printable: true,
    purpose: "Register of intangible carrying amounts.",
  },
  {
    id: "amortization-entries",
    group: "Fixed assets & capital",
    label: "Amortisation entries",
    description: "Periodic intangible charge",
    module: "assets",
    entityKey: "amortization-entries",
    href: "/assets?view=amortization-entries",
    printable: true,
    purpose: "Amortises intangibles over useful life.",
  },
  {
    id: "leases",
    group: "Fixed assets & capital",
    label: "Leases (IFRS 16)",
    description: "Right-of-use contracts",
    module: "assets",
    entityKey: "leases",
    href: "/assets?view=leases",
    printable: true,
    purpose: "Lease liability and right-of-use asset tracking.",
  },
  {
    id: "capital-accounts",
    group: "Fixed assets & capital",
    label: "Capital accounts",
    description: "Owner equity",
    module: "capital",
    entityKey: "capital-accounts",
    href: "/capital?view=capital-accounts",
    printable: true,
    purpose: "Owner capital and equity contributions.",
  },
  {
    id: "share-based-payments",
    group: "Fixed assets & capital",
    label: "Share-based payments",
    description: "IFRS 2 awards",
    module: "capital",
    entityKey: "share-based-payments",
    href: "/capital?view=share-based-payments",
    printable: true,
    purpose: "Equity-settled staff compensation.",
  },

  // —— Books ——
  {
    id: "journal-entries",
    group: "Books & journals",
    label: "Journal entries",
    description: "Manual double-entry",
    module: "accounts",
    entityKey: "journal-entries",
    href: "/accounts?view=journal-entries",
    printable: true,
    purpose: "Accruals, adjustments, corrections not driven by source docs.",
  },
  {
    id: "recurring-journal-entries",
    group: "Books & journals",
    label: "Recurring journal entries",
    description: "Standing accruals",
    module: "accounts",
    entityKey: "recurring-journal-entries",
    href: "/accounts?view=recurring-journal-entries",
    printable: false,
    purpose: "Rent, depreciation schedules and other repeating journals.",
  },
  {
    id: "matching-entries",
    group: "Books & journals",
    label: "Matching entries",
    description: "Allocation / clearing",
    module: "accounts",
    entityKey: "matching-entries",
    href: "/accounts?view=matching-entries",
    printable: true,
    purpose: "Links payments to invoices and clears control accounts.",
  },
  {
    id: "provisions",
    group: "Books & journals",
    label: "Provisions",
    description: "IAS 37 liabilities",
    module: "accounts",
    entityKey: "provisions",
    href: "/accounts?view=provisions",
    printable: true,
    purpose: "Warranty, legal and other uncertain liabilities.",
  },

  // —— Tax ——
  {
    id: "withholding-tax-receipts",
    group: "Tax & compliance",
    label: "Withholding tax receipts (sales)",
    description: "WHT certificates from customers",
    module: "sales",
    entityKey: "withholding-tax-receipts",
    href: "/sales?view=withholding-tax-receipts",
    printable: true,
    purpose: "Evidence of tax withheld by customers — claimable against income tax.",
  },
  {
    id: "withholding-tax",
    group: "Tax & compliance",
    label: "Withholding tax (purchases)",
    description: "WHT on supplier payments",
    module: "purchases",
    entityKey: "withholding-tax",
    href: "/purchases?view=withholding-tax",
    printable: true,
    purpose: "Tax withheld when paying suppliers — remitted to URA.",
  },
  {
    id: "customer-statements",
    group: "Tax & compliance",
    label: "Customer statements",
    description: "AR statements",
    module: "reports",
    entityKey: "customer-statements",
    href: "/reports?view=customer-statements",
    printable: false,
    purpose: "Period statement of account sent to customers.",
  },
  {
    id: "supplier-statements",
    group: "Tax & compliance",
    label: "Supplier statements",
    description: "AP statements",
    module: "reports",
    entityKey: "supplier-statements",
    href: "/reports?view=supplier-statements",
    printable: false,
    purpose: "Reconcile supplier balances to their statements.",
  },
  {
    id: "tax-summary",
    group: "Tax & compliance",
    label: "Tax summary",
    description: "VAT / tax overview",
    module: "reports",
    entityKey: "tax-summary",
    href: "/reports?view=tax-summary",
    printable: false,
    purpose: "Period tax totals for return preparation.",
  },
  {
    id: "trial-balance",
    group: "Tax & compliance",
    label: "Trial balance",
    description: "Books control report",
    module: "reports",
    entityKey: "trial-balance",
    href: "/reports?view=trial-balance",
    printable: false,
    purpose: "Confirms debits equal credits before financial statements.",
  },
  {
    id: "profit-and-loss",
    group: "Tax & compliance",
    label: "Profit & loss",
    description: "Income statement",
    module: "reports",
    entityKey: "profit-and-loss",
    href: "/reports?view=profit-and-loss",
    printable: false,
    purpose: "Period performance report.",
  },
  {
    id: "balance-sheet",
    group: "Tax & compliance",
    label: "Balance sheet",
    description: "Statement of financial position",
    module: "reports",
    entityKey: "balance-sheet",
    href: "/reports?view=balance-sheet",
    printable: false,
    purpose: "Assets, liabilities and equity at period end.",
  },
];

export function accountingDocsByGroup() {
  return ACCOUNTING_DOCUMENT_GROUPS.map((group) => ({
    group,
    items: REQUIRED_ACCOUNTING_DOCUMENTS.filter((doc) => doc.group === group),
  }));
}

/** Entities that should support PDF / print beyond the commercial core. */
export const ACCOUNTING_PRINTABLE_ENTITY_KEYS = REQUIRED_ACCOUNTING_DOCUMENTS.filter(
  (doc) => doc.printable,
).map((doc) => doc.entityKey);
