/** Field keys rendered by PayslipComputePanel — keep out of the panel chunk. */
export const PAYSLIP_COMPUTE_KEYS = new Set([
  "employee",
  "employeeId",
  "bankAccount",
  "bankCode",
  "accountNumber",
  "department",
  "phone",
  "basicPay",
  "daysInPeriod",
  "daysWorked",
  "dailyRate",
  "adjustedBasic",
  "earnings",
  "paye",
  "nssfEmployee",
  "nssfEmployer",
  "advances",
  "arrears",
  "deductions",
  "contributions",
  "netPay",
  "amount",
]);
