/**
 * AUTO-GENERATED by scripts/generate-domain-models.ts — DO NOT EDIT.
 * Domain catalog for tooling. Runtime reads/writes Postgres entity_records
 * via the Go API (/api/records/:module/:entity). No Prisma.
 */

export type PageEntityMeta = {
  module: string;
  storageModule: string;
  entity: string;
  label: string;
  table: string | null;
  columns: string[];
};

export const PAGE_ENTITY_CATALOG: PageEntityMeta[] = 
[
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "accounting-operations",
    "label": "Accounting Operations",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "activities",
    "label": "Activities",
    "table": "page_activities",
    "columns": [
      "name",
      "code",
      "project",
      "phase",
      "startDate",
      "dueDate",
      "progressPercent",
      "status",
      "description"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "aged-payables",
    "label": "Aged Payables",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "aged-receivables",
    "label": "Aged Receivables",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "ai-insights",
    "label": "AI Insights",
    "table": "page_ai_insights",
    "columns": [
      "reference",
      "date",
      "source",
      "kind",
      "summary",
      "confidence",
      "status",
      "details",
      "recommendedActions"
    ]
  },
  {
    "module": "assets",
    "storageModule": "assets",
    "entity": "amortization-entries",
    "label": "Amortization Entries",
    "table": "page_amortization_entries",
    "columns": [
      "reference",
      "date",
      "asset",
      "amount",
      "description",
      "status"
    ]
  },
  {
    "module": "documents",
    "storageModule": "documents",
    "entity": "attachments",
    "label": "Attachments",
    "table": "page_attachments",
    "columns": [
      "name",
      "folder",
      "linkedTo",
      "fileUrl",
      "date",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "attendance",
    "label": "Attendance",
    "table": "page_attendance",
    "columns": [
      "reference",
      "date",
      "employee",
      "department",
      "site",
      "block",
      "clockIn",
      "clockOut",
      "hours",
      "latitude",
      "longitude",
      "accuracyMeters",
      "wifiBssid",
      "verification",
      "verificationNote",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "balance-sheet",
    "label": "Balance Sheet",
    "table": null,
    "columns": [
      "name",
      "type",
      "from",
      "to",
      "basis",
      "status"
    ]
  },
  {
    "module": "banking",
    "storageModule": "banking",
    "entity": "bank-and-cash-accounts",
    "label": "Bank & Cash Accounts",
    "table": "page_bank_and_cash_accounts",
    "columns": [
      "name",
      "glAccount",
      "type",
      "institution",
      "accountNumber",
      "currency",
      "openingBalance",
      "division",
      "code",
      "balance",
      "uncategorizedReceipts",
      "uncategorizedPayments",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "bank-reconciliation",
    "label": "Bank Reconciliation",
    "table": null,
    "columns": [
      "reference",
      "date",
      "account",
      "statementBalance",
      "systemBalance",
      "discrepancy",
      "status"
    ]
  },
  {
    "module": "banking",
    "storageModule": "banking",
    "entity": "bank-statements",
    "label": "Bank Statements",
    "table": "page_bank_statements",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "batch-records",
    "label": "Job Cards",
    "table": "page_batch_records",
    "columns": [
      "workOrder",
      "date",
      "workCenter",
      "technician",
      "hours",
      "meterReading",
      "partsUsed",
      "completion",
      "status",
      "workDone",
      "attachments"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "benchmark-studies",
    "label": "Benchmark Studies",
    "table": "page_benchmark_studies",
    "columns": [
      "reference",
      "date",
      "workSystem",
      "benchmarkSource",
      "baselineScore",
      "benchmarkScore",
      "gap",
      "owner",
      "status",
      "findings",
      "attachments"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "bill-of-materials",
    "label": "Bill of Materials",
    "table": "page_bill_of_materials",
    "columns": [
      "name",
      "code",
      "finishedItem",
      "version",
      "components",
      "batchSize",
      "unit",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "billable-expenses",
    "label": "Billable Expenses",
    "table": "page_billable_expenses",
    "columns": [
      "reference",
      "date",
      "claimant",
      "description",
      "account",
      "division",
      "amount",
      "attachments",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "billable-time",
    "label": "Billable Time",
    "table": "page_billable_time",
    "columns": [
      "date",
      "customer",
      "description",
      "hours",
      "rate",
      "amount",
      "division",
      "status"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "bills",
    "label": "Bills (alias)",
    "table": "page_bills",
    "columns": [
      "reference",
      "date",
      "party",
      "amount",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "blocks",
    "label": "Blocks",
    "table": "page_blocks",
    "columns": [
      "name",
      "code",
      "site",
      "latitude",
      "longitude",
      "radiusMeters",
      "wifiBssids",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "budget-vs-actual",
    "label": "Budget vs Actual",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "capa-actions",
    "label": "CAPA Actions",
    "table": "page_capa_actions",
    "columns": [
      "reference",
      "date",
      "ncr",
      "action",
      "owner",
      "dueDate",
      "kind",
      "status",
      "effectiveness",
      "attachments"
    ]
  },
  {
    "module": "capital",
    "storageModule": "capital",
    "entity": "capital-accounts",
    "label": "Capital Accounts",
    "table": "page_capital_accounts",
    "columns": [
      "name",
      "code",
      "owner",
      "openingBalance",
      "balance",
      "status"
    ]
  },
  {
    "module": "capital",
    "storageModule": "capital",
    "entity": "capital-subaccounts",
    "label": "Capital Subaccounts",
    "table": "page_capital_subaccounts",
    "columns": [
      "name",
      "code",
      "type",
      "description",
      "status"
    ]
  },
  {
    "module": "logistics",
    "storageModule": "logistics",
    "entity": "carriers",
    "label": "Carriers",
    "table": "page_carriers",
    "columns": [
      "name",
      "code",
      "phone",
      "email",
      "contactPerson",
      "address",
      "type",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "cash-flow",
    "label": "Cash Flow",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "cash-flow-indirect",
    "label": "Cash Flow Indirect",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "cash-sessions",
    "label": "Cash Sessions",
    "table": "page_cash_sessions",
    "columns": [
      "reference",
      "date",
      "register",
      "cashier",
      "openingFloat",
      "expectedCash",
      "countedCash",
      "variance",
      "status",
      "notes"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "chart-of-accounts",
    "label": "Chart of Accounts",
    "table": "page_chart_of_accounts",
    "columns": [
      "kind",
      "name",
      "code",
      "type",
      "group",
      "parentGroup",
      "currency",
      "division",
      "openingBalance",
      "balance",
      "status"
    ]
  },
  {
    "module": "crm",
    "storageModule": "crm",
    "entity": "complaints",
    "label": "Complaints",
    "table": "page_complaints",
    "columns": [
      "reference",
      "date",
      "customer",
      "contact",
      "category",
      "priority",
      "description",
      "assignedTo",
      "salesOrder",
      "resolvedDate",
      "status",
      "resolution"
    ]
  },
  {
    "module": "crm",
    "storageModule": "crm",
    "entity": "contacts",
    "label": "Contacts",
    "table": "page_contacts",
    "columns": [
      "name",
      "code",
      "customer",
      "title",
      "phone",
      "email",
      "role",
      "notes",
      "status"
    ]
  },
  {
    "module": "contract-manager",
    "storageModule": "projects",
    "entity": "contractor-invoices",
    "label": "Contractor Invoices",
    "table": "page_contractor_invoices",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "supplier",
      "project",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "contract-manager",
    "storageModule": "projects",
    "entity": "contractor-ledgers",
    "label": "Contractor Ledgers",
    "table": null,
    "columns": [
      "account",
      "code",
      "debit",
      "credit",
      "balance",
      "asOf",
      "status"
    ]
  },
  {
    "module": "contract-manager",
    "storageModule": "projects",
    "entity": "contractors",
    "label": "Contractors",
    "table": "page_contractors",
    "columns": [
      "name",
      "company",
      "code",
      "username",
      "type",
      "address",
      "phone",
      "email",
      "paymentDetails",
      "trade",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "control-account-reconciliation",
    "label": "Control Account Reconciliation",
    "table": null,
    "columns": [
      "name",
      "code",
      "category",
      "group",
      "cashFlow",
      "status"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "control-accounts",
    "label": "Control Accounts",
    "table": "page_control_accounts",
    "columns": [
      "name",
      "code",
      "category",
      "group",
      "cashFlow",
      "status"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "cost-models",
    "label": "Cost Models",
    "table": "page_cost_models",
    "columns": [
      "name",
      "code",
      "product",
      "materialCost",
      "labourCost",
      "energyCost",
      "packagingCost",
      "wasteCost",
      "totalCost",
      "targetPrice",
      "marginPercent",
      "status",
      "assumptions"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "create-payroll",
    "label": "Create Payroll",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "credit-notes",
    "label": "Credit Notes",
    "table": "page_credit_notes",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "customer-ledgers",
    "label": "Customer Ledgers",
    "table": null,
    "columns": [
      "account",
      "code",
      "debit",
      "credit",
      "balance",
      "asOf",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "customer-portals",
    "label": "Customer Portals",
    "table": "page_customer_portals",
    "columns": [
      "customer",
      "quotes",
      "orders",
      "invoices",
      "creditNotes",
      "deliveryNotes",
      "portalUrl",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "customer-statements",
    "label": "Customer Statements",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "customers",
    "label": "Customers",
    "table": "page_customers",
    "columns": [
      "name",
      "code",
      "email",
      "address",
      "currency",
      "creditLimit",
      "balance",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "customers-receivable",
    "label": "Customers Receivable (alias)",
    "table": "page_customers_receivable",
    "columns": [
      "name",
      "code",
      "status"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "cycle-time-studies",
    "label": "Cycle Time Studies",
    "table": "page_cycle_time_studies",
    "columns": [
      "reference",
      "date",
      "workSystem",
      "step",
      "samples",
      "avgMinutes",
      "bestMinutes",
      "worstMinutes",
      "observedBy",
      "status",
      "notes"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "daily-closings",
    "label": "Daily Closings",
    "table": "page_daily_closings",
    "columns": [
      "reference",
      "date",
      "register",
      "salesTotal",
      "returnsTotal",
      "netTotal",
      "cashTotal",
      "cardTotal",
      "mobileTotal",
      "bankDeposit",
      "depositTo",
      "registerAccount",
      "status",
      "notes"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "debit-notes",
    "label": "Debit Notes",
    "table": "page_debit_notes",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "documents",
    "storageModule": "documents",
    "entity": "deleted-records",
    "label": "Deleted Records",
    "table": "page_deleted_records",
    "columns": [
      "timestamp",
      "deletedBy",
      "deletedByEmail",
      "deletedByUsername",
      "deletedByUserId",
      "deletedByRole",
      "module",
      "entity",
      "recordLabel",
      "recordId",
      "name",
      "reference",
      "code",
      "date",
      "party",
      "account",
      "amount",
      "currency",
      "type",
      "originalStatus",
      "description",
      "details",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "delivery-notes",
    "label": "Delivery Notes",
    "table": "page_delivery_notes",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "delivery-runs",
    "label": "Delivery Runs",
    "table": "page_delivery_runs",
    "columns": [
      "reference",
      "date",
      "route",
      "vehicle",
      "driver",
      "orders",
      "status",
      "notes"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "departments",
    "label": "Departments",
    "table": "page_departments",
    "columns": [
      "name",
      "code",
      "manager",
      "costCenter",
      "location",
      "headcount",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "assets",
    "storageModule": "assets",
    "entity": "depreciation-entries",
    "label": "Depreciation Entries",
    "table": "page_depreciation_entries",
    "columns": [
      "reference",
      "date",
      "asset",
      "amount",
      "description",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "dining-tables",
    "label": "Dining Tables",
    "table": "page_dining_tables",
    "columns": [
      "name",
      "code",
      "seats",
      "area",
      "status"
    ]
  },
  {
    "module": "logistics",
    "storageModule": "logistics",
    "entity": "dispatch-board",
    "label": "Dispatch Board",
    "table": "page_dispatch_board",
    "columns": [
      "reference",
      "date",
      "shipment",
      "vehicle",
      "driver",
      "route",
      "departAt",
      "returnAt",
      "status",
      "notes"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "distribution-orders",
    "label": "Distribution Orders",
    "table": "page_distribution_orders",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "distribution-returns",
    "label": "Distribution Returns",
    "table": "page_distribution_returns",
    "columns": [
      "reference",
      "date",
      "customer",
      "distributionOrder",
      "salesOrder",
      "warehouse",
      "reason",
      "condition",
      "quantity",
      "item",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "division-exception-report",
    "label": "Division Exception Report",
    "table": null,
    "columns": [
      "name",
      "type",
      "from",
      "to",
      "basis",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "document-requests",
    "label": "Document Requests",
    "table": "page_document_requests",
    "columns": [
      "reference",
      "date",
      "project",
      "phase",
      "requestedBy",
      "documentType",
      "description",
      "neededBy",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "downtime-logs",
    "label": "Downtime",
    "table": "page_downtime_logs",
    "columns": [
      "date",
      "startTime",
      "workCenter",
      "reason",
      "category",
      "reportedBy",
      "kgLost",
      "minutes",
      "status",
      "notes"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "drivers",
    "label": "Drivers",
    "table": "page_drivers",
    "columns": [
      "name",
      "code",
      "employee",
      "phone",
      "email",
      "nationalId",
      "licenseNumber",
      "licenseClass",
      "licenseExpiry",
      "licenseIssueDate",
      "vehicle",
      "department",
      "hireDate",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "employees",
    "label": "Employees",
    "table": "page_employees",
    "columns": [
      "name",
      "code",
      "gender",
      "dateOfBirth",
      "nationality",
      "biodata",
      "nationalId",
      "tin",
      "nssfNumber",
      "phone",
      "email",
      "address",
      "city",
      "emergencyContact",
      "emergencyPhone",
      "nextOfKin",
      "nextOfKinRelation",
      "department",
      "jobTitle",
      "manager",
      "workLocation",
      "hireDate",
      "probationEnd",
      "contractEnd",
      "contractType",
      "bankAccount",
      "bankCode",
      "accountNumber",
      "basicPay",
      "housingAllowance",
      "transportAllowance",
      "otherAllowances",
      "leaveBalance",
      "currency",
      "residentStatus",
      "medicalInsurer",
      "medicalPolicy",
      "medicalExpiry",
      "lifeInsurer",
      "lifePolicy",
      "lifeExpiry",
      "insuranceNotes",
      "terminationDate",
      "attachments",
      "notes",
      "balance",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "equipment-and-vehicle-requests",
    "label": "Equipment & Vehicle Requests",
    "table": "page_equipment_and_vehicle_requests",
    "columns": [
      "reference",
      "date",
      "project",
      "phase",
      "requestedBy",
      "requestType",
      "description",
      "neededBy",
      "returnDate",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "expense-claims",
    "storageModule": "expense-claims",
    "entity": "expense-claim-payers",
    "label": "Expense Claim Payers",
    "table": "page_expense_claim_payers",
    "columns": [
      "name",
      "payerType",
      "openingBalance",
      "balance",
      "status"
    ]
  },
  {
    "module": "expense-claims",
    "storageModule": "expense-claims",
    "entity": "expense-claims",
    "label": "Expense Claims",
    "table": "page_expense_claims",
    "columns": [
      "reference",
      "date",
      "claimant",
      "description",
      "account",
      "division",
      "amount",
      "attachments",
      "status"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "experiments",
    "label": "Experiments",
    "table": "page_experiments",
    "columns": [
      "reference",
      "date",
      "product",
      "hypothesis",
      "variable",
      "control",
      "method",
      "batchSize",
      "owner",
      "result",
      "status",
      "observations",
      "conclusion",
      "attachments"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "field-audit-log",
    "label": "Field Audit Log",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "assets",
    "storageModule": "assets",
    "entity": "fixed-assets",
    "label": "Fixed Assets",
    "table": "page_fixed_assets",
    "columns": [
      "code",
      "name",
      "quantity",
      "registrationNumber",
      "serialModel",
      "category",
      "group",
      "location",
      "physicalCondition",
      "acquired",
      "currency",
      "entryType",
      "cost",
      "otherCosts",
      "totalAcquisitionCost",
      "accumulatedDepreciation",
      "paidFrom",
      "depreciationMethod",
      "rate",
      "usefulLifeYears",
      "bookValue",
      "status"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "fleet-cost-report",
    "label": "Fleet Cost Report",
    "table": null,
    "columns": [
      "name"
    ]
  },
  {
    "module": "documents",
    "storageModule": "documents",
    "entity": "folders",
    "label": "Folders",
    "table": "page_folders",
    "columns": [
      "name",
      "description",
      "owner",
      "status"
    ]
  },
  {
    "module": "crm",
    "storageModule": "crm",
    "entity": "follow-ups",
    "label": "Follow-ups",
    "table": "page_follow_ups",
    "columns": [
      "reference",
      "date",
      "type",
      "subject",
      "relatedTo",
      "contact",
      "owner",
      "dueDate",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "forecast-pandl",
    "label": "Forecast P&L",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "formulations",
    "label": "Formulations",
    "table": "page_formulations",
    "columns": [
      "name",
      "code",
      "product",
      "version",
      "ingredients",
      "targetYield",
      "roastTemp",
      "processTime",
      "owner",
      "status",
      "procedure",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "fuel-logs",
    "label": "Fuel Logs",
    "table": "page_fuel_logs",
    "columns": [
      "reference",
      "date",
      "vehicle",
      "driver",
      "fuelRequest",
      "litres",
      "odometer",
      "amount",
      "currency",
      "station",
      "expenseAccount",
      "bankAccount",
      "paidFrom",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "fuel-requests",
    "label": "Fuel Requests",
    "table": "page_fuel_requests",
    "columns": [
      "reference",
      "date",
      "vehicle",
      "driver",
      "department",
      "litres",
      "amount",
      "currency",
      "purpose",
      "neededBy",
      "station",
      "bankAccount",
      "fuelLog",
      "fulfilledDate",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "gantt-chart",
    "label": "Gantt Chart",
    "table": null,
    "columns": []
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "gap-analyses",
    "label": "Gap Analyses",
    "table": "page_gap_analyses",
    "columns": [
      "reference",
      "date",
      "workSystem",
      "benchmarkStudy",
      "gap",
      "impact",
      "owner",
      "status",
      "rootCause",
      "recommendation"
    ]
  },
  {
    "module": "security",
    "storageModule": "security",
    "entity": "gate-passes",
    "label": "Gate Passes",
    "table": "page_gate_passes",
    "columns": [
      "reference",
      "date",
      "passType",
      "person",
      "employee",
      "vehicle",
      "department",
      "fromLocation",
      "toLocation",
      "purpose",
      "validFrom",
      "validTo",
      "gate",
      "authorizedBy",
      "timeOut",
      "timeIn",
      "items",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "requests",
    "storageModule": "requests",
    "entity": "general-requests",
    "label": "General Requests",
    "table": "page_general_requests",
    "columns": [
      "reference",
      "date",
      "requestedBy",
      "department",
      "category",
      "subject",
      "description",
      "amount",
      "currency",
      "neededBy",
      "priority",
      "approver",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "goods-receipts",
    "label": "Goods Receipts",
    "table": "page_goods_receipts",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "green-bean-intakes",
    "label": "Green Bean Intakes",
    "table": "page_green_bean_intakes",
    "columns": [
      "reference",
      "date",
      "supplier",
      "origin",
      "variety",
      "process",
      "harvest",
      "bags",
      "quantity",
      "moisture",
      "sampleScore",
      "grade",
      "location",
      "certificate",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "documents",
    "storageModule": "documents",
    "entity": "history",
    "label": "History",
    "table": "page_history",
    "columns": [
      "timestamp",
      "user",
      "email",
      "username",
      "userId",
      "action",
      "module",
      "entity",
      "recordLabel",
      "details",
      "status"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "hold-and-release-log",
    "label": "Hold & Release Log",
    "table": "page_hold_and_release_log",
    "columns": [
      "reference",
      "date",
      "batch",
      "event",
      "reason",
      "by",
      "location",
      "status",
      "notes"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "holidays",
    "label": "Holidays",
    "table": "page_holidays",
    "columns": [
      "name",
      "date",
      "kind",
      "status",
      "notes"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "improvement-actions",
    "label": "Improvement Actions",
    "table": "page_improvement_actions",
    "columns": [
      "reference",
      "date",
      "workSystem",
      "gap",
      "action",
      "owner",
      "dueDate",
      "status",
      "evidence",
      "attachments"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "in-process-checks",
    "label": "In-process Checks",
    "table": "page_in_process_checks",
    "columns": [
      "reference",
      "date",
      "stage",
      "batch",
      "parameter",
      "target",
      "actual",
      "checkedBy",
      "result",
      "status",
      "notes"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "incoming-inspections",
    "label": "Incoming Inspections",
    "table": "page_incoming_inspections",
    "columns": [
      "reference",
      "date",
      "sourceLot",
      "item",
      "sampleSize",
      "moisture",
      "defectCount",
      "inspector",
      "result",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "instrument-calibrations",
    "label": "Instrument Calibrations",
    "table": "page_instrument_calibrations",
    "columns": [
      "reference",
      "date",
      "instrument",
      "serial",
      "standard",
      "performedBy",
      "nextDue",
      "result",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "assets",
    "storageModule": "assets",
    "entity": "intangible-assets",
    "label": "Intangible Assets",
    "table": "page_intangible_assets",
    "columns": [
      "name",
      "code",
      "category",
      "acquired",
      "currency",
      "entryType",
      "cost",
      "accumulatedAmortization",
      "paidFrom",
      "rate",
      "bookValue",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "integrity-tests",
    "label": "Integrity Tests",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "banking",
    "storageModule": "banking",
    "entity": "inter-account-transfers",
    "label": "Inter Account Transfers",
    "table": "page_inter_account_transfers",
    "columns": [
      "reference",
      "date",
      "from",
      "to",
      "amount",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-items",
    "label": "Inventory Items",
    "table": "page_inventory_items",
    "columns": [
      "name",
      "code",
      "unit",
      "description",
      "location",
      "openingStock",
      "unitValue",
      "stockValue",
      "salesAccount",
      "salesPrice",
      "purchaseAccount",
      "reorderLevel",
      "closingStock",
      "closingValue",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-kits",
    "label": "Inventory Kits",
    "table": "page_inventory_kits",
    "columns": [
      "name",
      "code",
      "date",
      "components",
      "salesPrice",
      "taxCode",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-locations",
    "label": "Warehouses & Locations",
    "table": "page_inventory_locations",
    "columns": [
      "kind",
      "name",
      "code",
      "address",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-sales",
    "label": "Inventory Sales",
    "table": "page_inventory_sales",
    "columns": [
      "reference",
      "date",
      "party",
      "item",
      "location",
      "quantity",
      "unitPrice",
      "amount",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-transfers",
    "label": "Inventory Transfers",
    "table": "page_inventory_transfers",
    "columns": [
      "reference",
      "date",
      "item",
      "quantity",
      "from",
      "to",
      "receivedDate",
      "receivedBy",
      "description",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "inventory-value-summary",
    "label": "Inventory Value Summary",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "inventory-write-offs",
    "label": "Inventory Write-offs",
    "table": "page_inventory_write_offs",
    "columns": [
      "reference",
      "date",
      "item",
      "location",
      "quantity",
      "reasonType",
      "description",
      "allocation",
      "unitCost",
      "amount",
      "attachments",
      "evidenceNotes",
      "status"
    ]
  },
  {
    "module": "investments",
    "storageModule": "investments",
    "entity": "investments",
    "label": "Investments",
    "table": "page_investments",
    "columns": [
      "name",
      "code",
      "date",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "invoices",
    "label": "Invoices (alias)",
    "table": "page_invoices",
    "columns": [
      "reference",
      "date",
      "party",
      "amount",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "job-positions",
    "label": "Job Positions",
    "table": "page_job_positions",
    "columns": [
      "title",
      "code",
      "department",
      "employmentType",
      "headcount",
      "salaryMin",
      "salaryMax",
      "postedDate",
      "status",
      "description"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "journal-entries",
    "label": "Journal Entries",
    "table": "page_journal_entries",
    "columns": [
      "reference",
      "date",
      "division",
      "narration",
      "status"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "kpi-definitions",
    "label": "KPI Definitions",
    "table": "page_kpi_definitions",
    "columns": [
      "name",
      "code",
      "workSystem",
      "unit",
      "target",
      "formula",
      "owner",
      "frequency",
      "status",
      "notes"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "lab-methods",
    "label": "Lab Methods",
    "table": "page_lab_methods",
    "columns": [
      "name",
      "code",
      "version",
      "scope",
      "equipment",
      "status",
      "procedure",
      "acceptanceCriteria",
      "attachments"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "lab-requests",
    "label": "Lab Requests",
    "table": "page_lab_requests",
    "columns": [
      "reference",
      "date",
      "product",
      "requestedBy",
      "priority",
      "objective",
      "neededBy",
      "method",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "lab-results",
    "label": "Lab Results",
    "table": "page_lab_results",
    "columns": [
      "reference",
      "date",
      "sample",
      "trial",
      "method",
      "parameter",
      "value",
      "unit",
      "specLimit",
      "analyst",
      "result",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "lab-samples",
    "label": "Lab Samples",
    "table": "page_lab_samples",
    "columns": [
      "reference",
      "date",
      "source",
      "product",
      "location",
      "quantity",
      "unit",
      "condition",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "lab-trials",
    "label": "Lab Trials",
    "table": "page_lab_trials",
    "columns": [
      "reference",
      "date",
      "product",
      "hypothesis",
      "variable",
      "control",
      "method",
      "operator",
      "controlScore",
      "trialScore",
      "yieldPercent",
      "result",
      "status",
      "observations",
      "conclusion",
      "attachments"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "landed-costs",
    "label": "Landed Costs",
    "table": "page_landed_costs",
    "columns": [
      "reference",
      "date",
      "item",
      "purchase",
      "freight",
      "duty",
      "clearing",
      "otherCost",
      "amount",
      "allocationMethod",
      "division",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "late-payment-fees",
    "label": "Late Payment Fees",
    "table": "page_late_payment_fees",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "crm",
    "storageModule": "crm",
    "entity": "leads",
    "label": "Leads",
    "table": "page_leads",
    "columns": [
      "name",
      "code",
      "company",
      "phone",
      "email",
      "source",
      "stage",
      "owner",
      "nextFollowUp",
      "estimatedValue",
      "currency",
      "customer",
      "notes",
      "status"
    ]
  },
  {
    "module": "assets",
    "storageModule": "assets",
    "entity": "leases",
    "label": "Leases",
    "table": "page_leases",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "leave-requests",
    "label": "Leave Requests",
    "table": "page_leave_requests",
    "columns": [
      "reference",
      "employee",
      "leaveType",
      "startDate",
      "endDate",
      "days",
      "reason",
      "approver",
      "status",
      "attachments",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "ledgers",
    "label": "Ledgers",
    "table": null,
    "columns": [
      "account",
      "code",
      "debit",
      "credit",
      "balance",
      "asOf",
      "status"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "maintenance-requests",
    "label": "Maintenance Requests",
    "table": "page_maintenance_requests",
    "columns": [
      "reference",
      "date",
      "vehicle",
      "requestedBy",
      "priority",
      "description",
      "neededBy",
      "estimatedCost",
      "actualCost",
      "expenseAccount",
      "bankAccount",
      "supplier",
      "completedDate",
      "odometer",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "management-analysis",
    "label": "Management Analysis",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "matching-entries",
    "label": "Matching Entries",
    "table": "page_matching_entries",
    "columns": [
      "name",
      "code",
      "date",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "milestones",
    "label": "Milestones",
    "table": "page_milestones",
    "columns": [
      "name",
      "code",
      "project",
      "dueDate",
      "status",
      "description"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "non-conformances",
    "label": "Non-conformances",
    "table": "page_non_conformances",
    "columns": [
      "reference",
      "date",
      "source",
      "title",
      "severity",
      "owner",
      "status",
      "description",
      "rootCause",
      "attachments"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "non-inventory-items",
    "label": "Non-inventory Items",
    "table": "page_non_inventory_items",
    "columns": [
      "name",
      "code",
      "unit",
      "description",
      "salesAccount",
      "salesPrice",
      "purchaseAccount",
      "purchasePrice",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "notes-to-financial-statements",
    "label": "Notes to Financial Statements",
    "table": null,
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "onboarding",
    "label": "Onboarding",
    "table": "page_onboarding",
    "columns": [
      "reference",
      "employee",
      "position",
      "department",
      "startDate",
      "buddy",
      "checklist",
      "status",
      "notes"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "open-tickets",
    "label": "Open Tickets",
    "table": "page_open_tickets",
    "columns": [
      "reference",
      "date",
      "register",
      "session",
      "table",
      "serviceType",
      "customer",
      "lineCount",
      "subtotal",
      "tipAmount",
      "amount",
      "status"
    ]
  },
  {
    "module": "crm",
    "storageModule": "crm",
    "entity": "opportunities",
    "label": "Opportunities",
    "table": "page_opportunities",
    "columns": [
      "name",
      "code",
      "customer",
      "stage",
      "amount",
      "currency",
      "probability",
      "expectedClose",
      "owner",
      "salesOrder",
      "description",
      "status"
    ]
  },
  {
    "module": "requests",
    "storageModule": "requests",
    "entity": "oral-payment-requests",
    "label": "Oral Payment Requests",
    "table": "page_oral_payment_requests",
    "columns": [
      "reference",
      "date",
      "requestedBy",
      "department",
      "payee",
      "amount",
      "currency",
      "bankAccount",
      "purpose",
      "neededBy",
      "priority",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "other-comprehensive-income",
    "label": "Other Comprehensive Income",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "production",
    "entity": "packaging-runs",
    "label": "Packaging Runs",
    "table": "page_packaging_runs",
    "columns": [
      "reference",
      "date",
      "roastBatch",
      "finishedItem",
      "packSize",
      "plannedQuantity",
      "quantity",
      "packagingMaterial",
      "lotCode",
      "bestBefore",
      "line",
      "operator",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "packing-lists",
    "label": "Packing Lists",
    "table": "page_packing_lists",
    "columns": [
      "reference",
      "date",
      "distributionOrder",
      "pickingList",
      "packer",
      "packages",
      "packaging",
      "lines",
      "status",
      "notes"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "payment-requests",
    "label": "Payment Requests (IPC)",
    "table": "page_payment_requests",
    "columns": [
      "reference",
      "date",
      "project",
      "phase",
      "milestone",
      "department",
      "contractor",
      "payTo",
      "payee",
      "amount",
      "currency",
      "dueDate",
      "status",
      "bankAccount",
      "description",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "receipts-payments",
    "storageModule": "banking",
    "entity": "payment-rules",
    "label": "Payment Rules",
    "table": "page_payment_rules",
    "columns": [
      "name",
      "bankAccount",
      "descriptionContains",
      "party",
      "postingAccount",
      "taxCode",
      "status"
    ]
  },
  {
    "module": "receipts-payments",
    "storageModule": "banking",
    "entity": "payments",
    "label": "Payments",
    "table": "page_payments",
    "columns": [
      "reference",
      "date",
      "account",
      "party",
      "currency",
      "amount",
      "division",
      "appliedTo",
      "description",
      "postingAccount",
      "paidFrom",
      "bankAccount",
      "allocations",
      "paymentMethod",
      "allocation",
      "clearance",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "payroll-runs",
    "label": "Payroll Runs",
    "table": "page_payroll_runs",
    "columns": [
      "reference",
      "date",
      "requestedBy",
      "department",
      "employeeCount",
      "defaultDays",
      "grossTotal",
      "payeTotal",
      "nssfTotal",
      "amount",
      "currency",
      "purpose",
      "status",
      "overridesJson",
      "payslipsCreated",
      "payslipCount",
      "payslipIds",
      "attachments",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "payslip-items",
    "label": "Payslip Items",
    "table": "page_payslip_items",
    "columns": [
      "name",
      "kind",
      "expenseAccount",
      "liabilityAccount",
      "defaultRate",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "payslips",
    "label": "Payslips",
    "table": "page_payslips",
    "columns": [
      "reference",
      "date",
      "employee",
      "employeeId",
      "department",
      "bankAccount",
      "bankCode",
      "accountNumber",
      "phone",
      "basicPay",
      "dailyRate",
      "daysWorked",
      "adjustedBasic",
      "nssfEmployee",
      "paye",
      "advances",
      "arrears",
      "netPay",
      "nssfEmployer",
      "earnings",
      "deductions",
      "contributions",
      "daysInPeriod",
      "payrollRunId",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "phases",
    "label": "Phases",
    "table": "page_phases",
    "columns": [
      "name",
      "code",
      "project",
      "startDate",
      "dueDate",
      "progressPercent",
      "status",
      "description"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "picking-lists",
    "label": "Picking Lists",
    "table": "page_picking_lists",
    "columns": [
      "reference",
      "date",
      "distributionOrder",
      "warehouse",
      "picker",
      "lines",
      "pickedDate",
      "status",
      "notes"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "pilot-batches",
    "label": "Pilot Batches",
    "table": "page_pilot_batches",
    "columns": [
      "reference",
      "date",
      "formulation",
      "experiment",
      "plannedQuantity",
      "actualQuantity",
      "yield",
      "unitCost",
      "equipment",
      "operator",
      "result",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-locations",
    "label": "POS Locations",
    "table": "page_pos_locations",
    "columns": [
      "kind",
      "name",
      "code",
      "address",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-products",
    "label": "POS Products",
    "table": "page_pos_products",
    "columns": [
      "name",
      "code",
      "category",
      "unit",
      "description",
      "location",
      "openingStock",
      "unitValue",
      "stockValue",
      "salesAccount",
      "salesPrice",
      "reorderLevel",
      "closingStock",
      "closingValue",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-returns",
    "label": "POS Returns",
    "table": "page_pos_returns",
    "columns": [
      "reference",
      "date",
      "register",
      "originalSale",
      "item",
      "location",
      "quantity",
      "unitPrice",
      "amount",
      "account",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-sales",
    "label": "POS Sales",
    "table": "page_pos_sales",
    "columns": [
      "reference",
      "date",
      "register",
      "session",
      "item",
      "lineKind",
      "location",
      "table",
      "serviceType",
      "modifiers",
      "quantity",
      "unitPrice",
      "amount",
      "taxRate",
      "taxAmount",
      "taxAccount",
      "account",
      "salesAccount",
      "tender",
      "customer",
      "ticket",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-services",
    "label": "POS Services",
    "table": "page_pos_services",
    "columns": [
      "name",
      "code",
      "category",
      "description",
      "salesAccount",
      "salesPrice",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-stock-in",
    "label": "POS Stock In",
    "table": "page_pos_stock_in",
    "columns": [
      "reference",
      "date",
      "item",
      "location",
      "quantity",
      "unitCost",
      "stockValue",
      "supplier",
      "description",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "pos-terminal",
    "label": "POS Terminal",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "procurement-list",
    "label": "Procurement List",
    "table": "page_procurement_list",
    "columns": [
      "reference",
      "date",
      "project",
      "item",
      "quantity",
      "amount",
      "status",
      "notes"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "product-simulations",
    "label": "Product Simulations",
    "table": null,
    "columns": []
  },
  {
    "module": "inventory",
    "storageModule": "production",
    "entity": "production-orders",
    "label": "Production Orders",
    "table": "page_production_orders",
    "columns": [
      "reference",
      "date",
      "finishedItem",
      "recipe",
      "workCenter",
      "quantity",
      "unit",
      "materials",
      "materialCost",
      "nonInventoryCost",
      "finishedValue",
      "location",
      "division",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "production-plans",
    "label": "Production Plans",
    "table": "page_production_plans",
    "columns": [
      "reference",
      "date",
      "weekOf",
      "product",
      "plannedQuantity",
      "workCenter",
      "owner",
      "status",
      "notes"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "productivity-scores",
    "label": "Productivity Scores",
    "table": "page_productivity_scores",
    "columns": [
      "reference",
      "date",
      "workSystem",
      "period",
      "output",
      "labourHours",
      "score",
      "target",
      "owner",
      "status",
      "notes"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "profit-and-loss",
    "label": "Profit & Loss",
    "table": null,
    "columns": [
      "name",
      "type",
      "from",
      "to",
      "basis",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "profit-and-loss-by-class",
    "label": "Profit & Loss by Class",
    "table": null,
    "columns": [
      "name",
      "type",
      "from",
      "to",
      "basis",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "progress-certificates",
    "label": "Progress Certificates",
    "table": "page_progress_certificates",
    "columns": [
      "reference",
      "date",
      "project",
      "contractor",
      "amount",
      "status",
      "description"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "project-expenses",
    "label": "Project Expenses",
    "table": "page_project_expenses",
    "columns": [
      "reference",
      "date",
      "project",
      "amount",
      "account",
      "status",
      "description"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "project-managers",
    "label": "Project Managers",
    "table": "page_project_managers",
    "columns": [
      "name",
      "code",
      "username",
      "title",
      "department",
      "contractor",
      "email",
      "phone",
      "status",
      "notes"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "project-updates",
    "label": "Project Updates",
    "table": "page_project_updates",
    "columns": [
      "project",
      "phase",
      "activity",
      "progressPercent",
      "date",
      "updatedBy",
      "status",
      "description",
      "attachments"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "projects",
    "label": "New Project",
    "table": "page_projects",
    "columns": [
      "name",
      "contractor",
      "manager",
      "siteEngineer",
      "type",
      "startDate",
      "endDate",
      "currency",
      "budget",
      "progressPercent",
      "status",
      "description",
      "attachments"
    ]
  },
  {
    "module": "logistics",
    "storageModule": "logistics",
    "entity": "proof-of-delivery",
    "label": "Proof of Delivery",
    "table": "page_proof_of_delivery",
    "columns": [
      "reference",
      "date",
      "shipment",
      "customer",
      "receivedBy",
      "receiverPhone",
      "driver",
      "vehicle",
      "condition",
      "notes",
      "attachments",
      "status"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "provisions",
    "label": "Provisions",
    "table": "page_provisions",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "purchase-invoices",
    "label": "Purchase Invoices",
    "table": "page_purchase_invoices",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "purchase-orders",
    "label": "Purchase Orders",
    "table": "page_purchase_orders",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "purchase-quotes",
    "label": "Purchase Quotes",
    "table": "page_purchase_quotes",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "qa",
    "entity": "quality-checks",
    "label": "Quality Checks",
    "table": "page_quality_checks",
    "columns": [
      "reference",
      "date",
      "batch",
      "sample",
      "cuppingScore",
      "moisture",
      "roastColor",
      "grind",
      "defects",
      "checkedBy",
      "approvedBy",
      "result",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "receipts-payments",
    "storageModule": "banking",
    "entity": "receipt-rules",
    "label": "Receipt Rules",
    "table": "page_receipt_rules",
    "columns": [
      "name",
      "bankAccount",
      "descriptionContains",
      "party",
      "postingAccount",
      "taxCode",
      "status"
    ]
  },
  {
    "module": "receipts-payments",
    "storageModule": "banking",
    "entity": "receipts",
    "label": "Receipts",
    "table": "page_receipts",
    "columns": [
      "reference",
      "date",
      "account",
      "party",
      "currency",
      "amount",
      "division",
      "appliedTo",
      "description",
      "postingAccount",
      "depositTo",
      "bankAccount",
      "allocations",
      "paymentMethod",
      "allocation",
      "clearance",
      "status"
    ]
  },
  {
    "module": "banking",
    "storageModule": "banking",
    "entity": "reconciliations",
    "label": "Reconciliations",
    "table": "page_reconciliations",
    "columns": [
      "reference",
      "date",
      "account",
      "statementBalance",
      "systemBalance",
      "discrepancy",
      "status"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "recurring-journal-entries",
    "label": "Recurring Journal Entries",
    "table": "page_recurring_journal_entries",
    "columns": [
      "name",
      "party",
      "nextIssueDate",
      "interval",
      "amount",
      "account",
      "description",
      "until",
      "endDate",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "recurring-payslips",
    "label": "Recurring Payslips",
    "table": "page_recurring_payslips",
    "columns": [
      "name",
      "party",
      "nextIssueDate",
      "interval",
      "amount",
      "account",
      "description",
      "until",
      "endDate",
      "status"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "recurring-purchase-invoices",
    "label": "Recurring Purchase Invoices",
    "table": "page_recurring_purchase_invoices",
    "columns": [
      "name",
      "party",
      "nextIssueDate",
      "interval",
      "amount",
      "account",
      "description",
      "until",
      "endDate",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "recurring-sales-invoices",
    "label": "Recurring Sales Invoices",
    "table": "page_recurring_sales_invoices",
    "columns": [
      "name",
      "party",
      "nextIssueDate",
      "interval",
      "amount",
      "account",
      "description",
      "until",
      "endDate",
      "status"
    ]
  },
  {
    "module": "pos",
    "storageModule": "pos",
    "entity": "registers",
    "label": "Registers",
    "table": "page_registers",
    "columns": [
      "name",
      "code",
      "location",
      "account",
      "defaultSalesAccount",
      "status"
    ]
  },
  {
    "module": "qa",
    "storageModule": "qa",
    "entity": "release-decisions",
    "label": "Release Decisions",
    "table": "page_release_decisions",
    "columns": [
      "reference",
      "date",
      "batch",
      "product",
      "checks",
      "decidedBy",
      "decision",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "requisitions",
    "label": "Material Requests",
    "table": "page_requisitions",
    "columns": [
      "reference",
      "date",
      "project",
      "phase",
      "activity",
      "milestone",
      "contractor",
      "description",
      "quantity",
      "unit",
      "amount",
      "currency",
      "neededBy",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "revenue-contracts",
    "label": "Revenue Contracts",
    "table": "page_revenue_contracts",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "production",
    "entity": "roast-batches",
    "label": "Roast Batches",
    "table": "page_roast_batches",
    "columns": [
      "reference",
      "date",
      "productionOrder",
      "greenLot",
      "recipe",
      "roaster",
      "inputWeight",
      "outputWeight",
      "roastLoss",
      "chargeTemperature",
      "endTemperature",
      "roastTime",
      "operator",
      "status",
      "profileNotes",
      "attachments"
    ]
  },
  {
    "module": "logistics",
    "storageModule": "logistics",
    "entity": "routes",
    "label": "Routes",
    "table": "page_routes",
    "columns": [
      "name",
      "code",
      "zone",
      "fromLocation",
      "toLocation",
      "distanceKm",
      "estHours",
      "status",
      "notes"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "sales-invoices",
    "label": "Sales Invoices",
    "table": "page_sales_invoices",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "sales-orders",
    "label": "Sales Orders",
    "table": "page_sales_orders",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "sales-quotes",
    "label": "Sales Quotes",
    "table": "page_sales_quotes",
    "columns": [
      "reference",
      "date",
      "dueDate",
      "party",
      "currency",
      "division",
      "description",
      "tax",
      "amount",
      "amountPaid",
      "balanceDue",
      "status",
      "attachments"
    ]
  },
  {
    "module": "security",
    "storageModule": "security",
    "entity": "security-incidents",
    "label": "Security Incidents",
    "table": "page_security_incidents",
    "columns": [
      "reference",
      "date",
      "time",
      "type",
      "severity",
      "location",
      "reportedBy",
      "involved",
      "description",
      "actionTaken",
      "policeRef",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "sensory-panels",
    "label": "Sensory Panels",
    "table": "page_sensory_panels",
    "columns": [
      "reference",
      "date",
      "product",
      "panelists",
      "aroma",
      "flavor",
      "body",
      "acidity",
      "aftertaste",
      "overall",
      "defects",
      "result",
      "status",
      "notes"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "service-reminders",
    "label": "Service Reminders",
    "table": null,
    "columns": []
  },
  {
    "module": "capital",
    "storageModule": "capital",
    "entity": "share-based-payments",
    "label": "Share-based Payments",
    "table": "page_share_based_payments",
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "logistics",
    "storageModule": "logistics",
    "entity": "shipments",
    "label": "Shipments",
    "table": "page_shipments",
    "columns": [
      "reference",
      "date",
      "customer",
      "salesOrder",
      "deliveryNote",
      "fromLocation",
      "toLocation",
      "vehicle",
      "driver",
      "carrier",
      "route",
      "packages",
      "weightKg",
      "status",
      "eta",
      "deliveredDate",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "sites",
    "label": "Sites",
    "table": "page_sites",
    "columns": [
      "name",
      "code",
      "address",
      "latitude",
      "longitude",
      "radiusMeters",
      "wifiBssids",
      "status",
      "notes"
    ]
  },
  {
    "module": "rnd",
    "storageModule": "rnd",
    "entity": "spec-sheets",
    "label": "Spec Sheets",
    "table": "page_spec_sheets",
    "columns": [
      "name",
      "code",
      "product",
      "version",
      "moistureMin",
      "moistureMax",
      "cuppingMin",
      "roastLossMax",
      "packSize",
      "shelfLife",
      "labelRequirements",
      "status",
      "acceptanceCriteria",
      "attachments"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "special-accounts",
    "label": "Special Accounts",
    "table": "page_special_accounts",
    "columns": [
      "name",
      "code",
      "owner",
      "openingBalance",
      "balance",
      "status"
    ]
  },
  {
    "module": "lab",
    "storageModule": "lab",
    "entity": "stability-studies",
    "label": "Stability Studies",
    "table": "page_stability_studies",
    "columns": [
      "reference",
      "date",
      "product",
      "condition",
      "durationDays",
      "pullDate",
      "tests",
      "owner",
      "status",
      "notes",
      "attachments"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "statement-of-changes-in-equity",
    "label": "Statement of Changes in Equity",
    "table": null,
    "columns": [
      "name",
      "code",
      "description",
      "amount",
      "status"
    ]
  },
  {
    "module": "payroll",
    "storageModule": "payroll",
    "entity": "statutory-remittances",
    "label": "Statutory Remittances",
    "table": "page_statutory_remittances",
    "columns": [
      "reference",
      "date",
      "kind",
      "period",
      "amount",
      "paidFrom",
      "receiptNumber",
      "status",
      "notes"
    ]
  },
  {
    "module": "distribution",
    "storageModule": "distribution",
    "entity": "stock-allocations",
    "label": "Stock Allocations",
    "table": "page_stock_allocations",
    "columns": [
      "reference",
      "date",
      "salesOrder",
      "distributionOrder",
      "item",
      "warehouse",
      "quantity",
      "status",
      "notes"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "stock-in",
    "label": "Stock In",
    "table": "page_stock_in",
    "columns": [
      "reference",
      "date",
      "item",
      "location",
      "quantity",
      "unitCost",
      "stockValue",
      "supplier",
      "description",
      "status"
    ]
  },
  {
    "module": "inventory",
    "storageModule": "inventory",
    "entity": "stocktakes",
    "label": "Stocktakes",
    "table": "page_stocktakes",
    "columns": [
      "reference",
      "date",
      "location",
      "item",
      "systemQuantity",
      "countedQuantity",
      "variance",
      "unitCost",
      "amount",
      "countedBy",
      "approvedBy",
      "status",
      "notes"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "supplier-ledgers",
    "label": "Supplier Ledgers",
    "table": null,
    "columns": [
      "account",
      "code",
      "debit",
      "credit",
      "balance",
      "asOf",
      "status"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "supplier-statements",
    "label": "Supplier Statements",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "suppliers",
    "label": "Suppliers",
    "table": "page_suppliers",
    "columns": [
      "name",
      "code",
      "category",
      "contacts",
      "location",
      "email",
      "phone",
      "address",
      "currency",
      "openingBalanceDate",
      "openingBalances",
      "creditLimit",
      "balance",
      "status",
      "notes"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "suppliers-payable",
    "label": "Suppliers Payable (alias)",
    "table": "page_suppliers_payable",
    "columns": [
      "name",
      "code",
      "status"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "tasks",
    "label": "Tasks",
    "table": "page_tasks",
    "columns": [
      "name",
      "code",
      "project",
      "phase",
      "activity",
      "status",
      "description"
    ]
  },
  {
    "module": "reports",
    "storageModule": "reports",
    "entity": "tax-summary",
    "label": "Tax Summary",
    "table": null,
    "columns": [
      "name",
      "from",
      "to",
      "asOf",
      "basis",
      "status"
    ]
  },
  {
    "module": "accounts",
    "storageModule": "accounts",
    "entity": "trial-balance",
    "label": "Trial Balance",
    "table": null,
    "columns": [
      "account",
      "code",
      "debit",
      "credit",
      "balance",
      "asOf",
      "status"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "trip-requests",
    "label": "Trip Requests",
    "table": "page_trip_requests",
    "columns": [
      "reference",
      "date",
      "vehicle",
      "driver",
      "department",
      "fromLocation",
      "toLocation",
      "departDate",
      "returnDate",
      "purpose",
      "estimatedKm",
      "odometerStart",
      "odometerEnd",
      "actualKm",
      "completedDate",
      "status",
      "attachments",
      "notes",
      "amendmentReason",
      "originalAmount",
      "amountRevisionNote",
      "amendedBy",
      "amendedAt",
      "rejectionReason",
      "amendedReturnTo",
      "rejectedBy",
      "rejectedAt"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "variations-of-work",
    "label": "Variations of Work",
    "table": "page_variations_of_work",
    "columns": [
      "reference",
      "date",
      "project",
      "phase",
      "activity",
      "description",
      "amountImpact",
      "currency",
      "scheduleDays",
      "progressPercent",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "fleet",
    "storageModule": "fleet",
    "entity": "vehicles",
    "label": "Vehicles",
    "table": "page_vehicles",
    "columns": [
      "name",
      "code",
      "registration",
      "type",
      "makeModel",
      "driver",
      "fixedAsset",
      "department",
      "location",
      "odometer",
      "nextServiceKm",
      "nextServiceDate",
      "insuranceExpiry",
      "insuranceProvider",
      "insurancePolicy",
      "registrationExpiry",
      "acquired",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "security",
    "storageModule": "security",
    "entity": "visitor-passes",
    "label": "Visitor Passes",
    "table": "page_visitor_passes",
    "columns": [
      "reference",
      "date",
      "name",
      "company",
      "phone",
      "idNumber",
      "host",
      "department",
      "purpose",
      "expectedArrival",
      "expectedDeparture",
      "badgeNumber",
      "vehicle",
      "timeIn",
      "timeOut",
      "status",
      "attachments",
      "notes"
    ]
  },
  {
    "module": "purchases",
    "storageModule": "purchases",
    "entity": "withholding-tax",
    "label": "Withholding Tax",
    "table": "page_withholding_tax",
    "columns": [
      "reference",
      "date",
      "party",
      "invoice",
      "amount",
      "rate",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "sales",
    "storageModule": "sales",
    "entity": "withholding-tax-receipts",
    "label": "Withholding Tax Receipts",
    "table": "page_withholding_tax_receipts",
    "columns": [
      "reference",
      "date",
      "party",
      "invoice",
      "amount",
      "rate",
      "division",
      "description",
      "status"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "work-centers",
    "label": "Machines",
    "table": "page_work_centers",
    "columns": [
      "name",
      "code",
      "type",
      "section",
      "location",
      "criticality",
      "status",
      "capacityPerHour",
      "purchasedOn",
      "supervisor",
      "notes"
    ]
  },
  {
    "module": "projects",
    "storageModule": "projects",
    "entity": "work-programs",
    "label": "Work Programs",
    "table": "page_work_programs",
    "columns": [
      "name",
      "project",
      "phase",
      "activity",
      "scheduledStart",
      "scheduledEnd",
      "assignedTo",
      "status",
      "description",
      "attachments"
    ]
  },
  {
    "module": "benchmark",
    "storageModule": "benchmark",
    "entity": "work-systems",
    "label": "Work Systems",
    "table": "page_work_systems",
    "columns": [
      "name",
      "code",
      "owner",
      "area",
      "maturity",
      "status",
      "description",
      "criticalSteps",
      "attachments"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "yield-reports",
    "label": "Yield Reports",
    "table": "page_yield_reports",
    "columns": [
      "reference",
      "date",
      "batch",
      "product",
      "plannedQuantity",
      "actualQuantity",
      "yieldPercent",
      "wasteQuantity",
      "owner",
      "status",
      "notes"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "work-orders",
    "label": "Work Orders",
    "table": "page_work_orders",
    "columns": [
      "num",
      "title",
      "workCenter",
      "woType",
      "priority",
      "dueDate",
      "assignee",
      "status",
      "estimatedHours",
      "partsRequired",
      "estimatedCost",
      "pmTemplate",
      "checklist",
      "description",
      "attachments"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "pm-schedules",
    "label": "Preventive Schedules",
    "table": "page_pm_schedules",
    "columns": [
      "template",
      "workCenter",
      "nextDue",
      "templateName",
      "intervalDays",
      "lastDone",
      "status"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "pm-templates",
    "label": "PM Templates",
    "table": "page_pm_templates",
    "columns": [
      "code",
      "name",
      "assetCategory",
      "intervalDays",
      "checklist",
      "notes"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "spare-parts",
    "label": "Spare Parts",
    "table": "page_spare_parts",
    "columns": [
      "name",
      "code",
      "partNumber",
      "manufacturer",
      "fitsMachineTypes",
      "fitsMachines",
      "unit",
      "reorderLevel",
      "maxQty",
      "storeLocation",
      "status",
      "onHand",
      "available",
      "notes"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "reliability",
    "label": "Reliability",
    "table": "page_reliability",
    "columns": [
      "workCenter",
      "mtbfHours",
      "mttrHours",
      "availability",
      "failures",
      "status",
      "since"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "alerts",
    "label": "Alerts",
    "table": "page_alerts",
    "columns": [
      "date",
      "severity",
      "workCenter",
      "message",
      "status",
      "acknowledgedOn",
      "resolvedOn"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "recommendations",
    "label": "Recommendations",
    "table": "page_recommendations",
    "columns": [
      "date",
      "title",
      "workCenter",
      "kind",
      "confidence",
      "body",
      "status"
    ]
  },
  {
    "module": "production",
    "storageModule": "production",
    "entity": "technicians",
    "label": "Technicians",
    "table": "page_technicians",
    "columns": [
      "name",
      "role",
      "plant",
      "status"
    ]
  }
]
;

export const PAGE_ENTITY_BY_KEY = Object.fromEntries(
  PAGE_ENTITY_CATALOG.map((row) => [row.entity, row]),
) as Record<string, PageEntityMeta>;

export function pageTableForEntity(entity: string): PageEntityMeta | null {
  const row = PAGE_ENTITY_BY_KEY[entity];
  return row?.table ? row : null;
}

export function allPageTables(): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const row of PAGE_ENTITY_CATALOG) {
    if (!row.table || seen.has(row.table)) continue;
    seen.add(row.table);
    out.push(row.table);
  }
  return out;
}
