import { supportsDocumentLines } from "@/lib/document-lines";

/** Tiny check — avoid importing the 2k-line document-pdf module on every module page. */
export const DOCUMENT_PDF_ENTITIES = new Set([
  "sales-invoices",
  "purchase-invoices",
  "credit-notes",
  "debit-notes",
  "sales-quotes",
  "purchase-quotes",
  "sales-orders",
  "purchase-orders",
  "delivery-notes",
  "late-payment-fees",
  "billable-time",
  "billable-expenses",
  "revenue-contracts",
  "goods-receipts",
  "receipts",
  "payments",
  "inter-account-transfers",
  "reconciliations",
  "payslips",
  "statutory-remittances",
  "expense-claims",
  "inventory-transfers",
  "inventory-write-offs",
  "stock-in",
  "inventory-sales",
  "production-orders",
  "stocktakes",
  "landed-costs",
  "fixed-assets",
  "depreciation-entries",
  "intangible-assets",
  "amortization-entries",
  "leases",
  "capital-accounts",
  "share-based-payments",
  "journal-entries",
  "matching-entries",
  "provisions",
  "withholding-tax-receipts",
  "withholding-tax",
  "fuel-requests",
  "fuel-logs",
  "trip-requests",
  "maintenance-requests",
  "payment-requests",
  "oral-payment-requests",
  "pos-sales",
  "pos-returns",
  "daily-closings",
  "general-requests",
  "procurement-list",
]);

export function supportsDocumentPdf(entityKey: string) {
  return DOCUMENT_PDF_ENTITIES.has(entityKey) || supportsDocumentLines(entityKey);
}
